- name: ubuntu-packages
  hosts: ubuntu
  become: true
  tasks:
    - name: Install list of packages on ubuntu
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - htop
        - screen
        - fail2ban
        - firejail
        - python3
        - python3-pip
        - ufw
        - net-tools

        


