- name: Add backup key to authorized_keys
  hosts: all
  become: true
  tasks:
    - name: Run shell command to add immutable flag to all .ssh directories
      shell: chattr -i /home/*/.ssh
    - name: Run shell command to add immutable flag to all authorized_keys
      shell: chattr -i /home/*/.ssh/authorized_keys
  tasks:
    - name: Copy backup key to host
      copy:
        src: files/ssh/backup_key.pub
        dest: /home/*/.ssh/backup_key.pub
        owner: root
        group: root
        mode: 0600


  tasks:
    - name: Run shell command to add immutable flag to all .ssh directories
      shell: chattr +i /home/*/.ssh
    - name: Run shell command to add immutable flag to all authorized_keys
      shell: chattr +i /home/*/.ssh/authorized_keys
