- name: Run the system information audit
  hosts: all
  become: true
  tasks:
    - name: Copy audit.sh to remote host
      copy:
        src: scripts/audit.sh
        dest: ~/audit.sh
        mode: 0755
    - name: Run audit.sh as root and output to /tmp/audit.log
      become: true
      shell: ~/audit.sh > /tmp/audit.log || true
    - name: fetch audit.log
      fetch:
        src: /tmp/audit.log
        dest: ./fetch/{{ ansible_host }}_{{ ansible_date_time.iso8601 }}_audit.log
        flat: yes
