- name: Install fail2ban
  hosts: all
  become: true
  tasks:
    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
      when: ansible_os_family == "Debian"
    - name: Install fail2ban
      yum:
        name: fail2ban
        state: present
      when: ansible_os_family == "RedHat"
    - name: Copy fail2ban jail.local
      copy:
        src: fail2ban/jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: 0644
    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted
    - name: Enable fail2ban
      service:
        name: fail2ban
        enabled: yes
    - name: Restart sshd
      service:
        name: sshd
        state: restarted