# TODO: add honeypot installation and service

- name: Install endlessh tarpit
  hosts: honeypot_servers
  become: true
  tasks:
    - name: Install endlessh
      apt:
        name: endlessh
        state: present
      when: ansible_os_family == "Debian"
    - name: Install endlessh
      yum:
        name: endlessh
        state: present
      when: ansible_os_family == "RedHat"
    - name: Disable endlessh
      systemd:
        name: endlessh
        enabled: no
        state: stopped
    - name: Kill endlessh
      shell: if pgrep endlessh; then pkill endlessh; fi
    - name: Run endlessh in background
      shell: endlessh -d 1000 -p 2222 -v >> /var/log/endlessh.log 2>&1 &
    - name: Add endlessh /var/log/endlessh.log to /etc/audit/rules.d/endless.rules
      lineinfile:
        create: yes
        path: /etc/audit/rules.d/endless.rules
        line: '-w /var/log/endlessh.log -p wa -k endlessh'
    - name: Restart auditd
      systemd:
        name: auditd
        state: restarted
- name: Install FTP Honeypot
  hosts: honeypot_servers
  become: true
  tasks:
    - name: Copy ftppot.py to remote host
      copy:
        src: scripts/ftppot.py
        dest: /opt/ftppot.py
        mode: 0755
    - name: Run ftppot.py as root
      become: true
      script: /opt/ftppot.py
- name: Install HTTP Honeypot
  hosts: honeypot_servers
  become: true
  tasks:
    - name: Copy httppot.py to remote host
      copy:
        src: scripts/httppot.py
        dest: /opt/httppot.py
        mode: 0755
    - name: Run httppot.py as root
      become: true
      script: /opt/httppot.py

    