# TODO: add honeypot installation and service

- name: Install endlessh tarpit
  hosts: all
  become: true
  tasks:
    - name: Install endlessh
      apt:
        name: endlessh
        state: present
      when: ansible_os_family == "Debian"
    - name: Install endlessh
      yum:
        name: endlessh
        state: present
      when: ansible_os_family == "RedHat"
    - name: Clone fail2ban-endlessh repo
      ansible.builtin.git:
        repo: 'https://github.com/itskenny0/fail2ban-endlessh.git'
        dest: /home/f2b-endlessh
        clone: yes
        update: yes
    - name: Copy fail2ban action.d
      copy:
        src: /home/f2b-endlessh/action.d/endlessh.conf
        dest: /etc/fail2ban/action.d/endlessh.conf
        owner: root
        group: root
        # mode: 0644
    - name: Copy fail2ban jail.d
      copy:
        src: /home/f2b-endlessh/jail.d/endlessh.conf
        dest: /etc/fail2ban/jail.d/endlessh.conf
        owner: root
        group: root
        # mode: 0644
    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted