- name: Enable SELinux on RHEL based hosts
  hosts: linux
  become: true
  tasks:
    - name: Enable SELinux
      selinux:
        state: enforcing
        policy: targeted
      when: ansible_os_family == "RedHat"
- name: Enable AppArmor service on debian based hosts
  hosts: linux
  become: true
  tasks:
    - name: Enable AppArmor
      service:
        name: apparmor
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"