- name: ubuntu-packages
  hosts: ubuntu
  become: true
  tasks:
    - name: Install list of packages on ubuntu
      apt:
        name: ["vim", "htop", "screen", "firejail", "python3", "python3-pip", "net-tools", "bash-completion"]
        state: present
- name: centos-packages
  hosts: centos
  become: true
  tasks:
    - name: Install list of packages on centos
      yum:
        name: ["vim", "htop", "screen", "python3", "python3-pip", "net-tools","bash-completion"]
        state: present
  pre_tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
    - name: yum update
      yum:
        name: "*"
        state: latest
- name: Update all packages
  hosts: all
  become: true
  tasks:
    - name: Update all packages (apt-based)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
    - name: Update all packages (yum-based)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"


