- name: Disable root login
  hosts: linux
  become: true
  tasks:
    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
    - name: Add ssh warning banner
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Banner'
        line: 'Banner /etc/issue.net'
        state: present
    - name: Copy warning banner to host
      copy:
        src: ssh/issue.net
        dest: /etc/issue.net
        owner: root
        group: root
        mode: 0644
    - name: Disable PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
    - name: Add AuthenticaMethods publickey to sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthenticationMethods'
        line: 'AuthenticationMethods publickey'
        state: present
  pre_tasks:
    - name: Remove immutable flag from /etc/ssh/sshd_config
      shell: chattr -i /etc/ssh/sshd_config
  post_tasks:
    - name: Add immutable flag to /etc/ssh/sshd_config
      shell: chattr +i /etc/ssh/sshd_config
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
- name: Mark all authorized_keys as read-only
  hosts: all
  become: true
  tasks:
    - name: Run shell command to add immutable flag to all .ssh directories
      shell: chattr +i /home/*/.ssh
    - name: Run shell command to add immutable flag to all authorized_keys
      shell: chattr +i /home/*/.ssh/authorized_keys
