- name: Disable root login
  hosts: all
  become: true
  tasks:
    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
  pre_tasks:
    - name: Remove immutable flag from /etc/ssh/sshd_config
      shell: chattr -i /etc/ssh/sshd_config
  post_tasks:
    - name: Add immutable flag to /etc/ssh/sshd_config
      shell: chattr +i /etc/ssh/sshd_config
- name: Mark all authorized_keys as read-only
  hosts: all
  become: true
  tasks:
    - name: Run shell command to add immutable flag to all .ssh directories
      shell: chattr +i /home/*/.ssh
    - name: Run shell command to add immutable flag to all authorized_keys
      shell: chattr +i /home/*/.ssh/authorized_keys