- name: Deploy and configure wazuh agents
  hosts: wazuh_agents
  become: true 
  roles:
      - { role: libyanspider.wazuh_agent_role, wazuh_manager_ip: 10.13.0.14, wazuh_agent_group: "default" }
  tasks:
    - name: wazuh_agents
    copy:
      src: /wazuh/ossec.conf
      dest: /var/ossec/etc/ossec.conf
      owner: root
      group: root
      mode: 0644
  
      - name: Restart configured agents
      service:
      name: wazuh-agent
      state: restarted
      
